### ISSUE TITLE
TypeError: Cannot read property 'prototype' of null

### ISSUE THREAD

**Issue by artem-alek** [SyslogicNL/pdf-extractor#13]
Having this issue when trying to run test samples or any pdf. Any thoughts?

```
/Users/xxxxxx/projects/pdf-extractor/lib/pdfjs-utils/domfacade.js:117
Object.defineProperty(Canvas.prototype, "getContext", {
                             ^

TypeError: Cannot read property 'prototype' of null
    at Object.<anonymous> (/Users/xxxxxxx/projects/pdf-extractor/lib/pdfjs-utils/domfacade.js:117:30)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xxxxxx/projects/pdf-extractor/lib/PdfExtractor.js:4:19)
    at Module._compile (module.js:660:30)
```

**Comment by Hikariii** [comment]
It looks like https://github.com/SyslogicNL/pdf-extractor/blob/master/lib/pdfjs-utils/domfacade.js#L13 does not exist.
What version of jsdom do you have installed?

**Comment by Hikariii** [comment]
Closing this in lack of a response.
