### ISSUE TITLE
Issue rendering pdf images (imageObject)

### ISSUE THREAD

**Issue by Hikariii** [SyslogicNL/pdf-extractor#3]
## Fatal error:

```
Unhandled rejection TypeError: Image or Canvas expected
    at CanvasGraphics_paintJpegXObject [as paintJpegXObject] (/usr/src/app/node_modules/pdfjs-dist/build/pdf.js:14502:11)
    at CanvasGraphics_executeOperatorList [as executeOperatorList] (/usr/src/app/node_modules/pdfjs-dist/build/pdf.js:13624:22)
    at InternalRenderTask__next [as _next] (/usr/src/app/node_modules/pdfjs-dist/build/pdf.js:4682:39)
From previous event:
    at InternalRenderTask__scheduleNext [as _scheduleNext] (/usr/src/app/node_modules/pdfjs-dist/build/pdf.js:4675:36)
    at InternalRenderTask__continue [as _continue] (/usr/src/app/node_modules/pdfjs-dist/build/pdf.js:4668:14)
    at InternalRenderTask_operatorListChanged [as operatorListChanged] (/usr/src/app/node_modules/pdfjs-dist/build/pdf.js:4658:12)
    at PDFPageProxy_renderPageChunk [as _renderPageChunk] (/usr/src/app/node_modules/pdfjs-dist/build/pdf.js:3761:36)
    at WorkerTransport.transportRender (/usr/src/app/node_modules/pdfjs-dist/build/pdf.js:4250:14)
    at LoopbackPort.MessageHandler._onComObjOnMessage (/usr/src/app/node_modules/pdfjs-dist/build/pdf.js:1036:19)
    at LoopbackPort.<anonymous> (/usr/src/app/node_modules/pdfjs-dist/build/pdf.js:3835:20)
    at Array.forEach (<anonymous>)
    at /usr/src/app/node_modules/pdfjs-dist/build/pdf.js:3834:27
From previous event:
    at LoopbackPort.postMessage (/usr/src/app/node_modules/pdfjs-dist/build/pdf.js:3833:22)
    at MessageHandler.postMessage (/usr/src/app/node_modules/pdfjs-dist/build/pdf.worker.js:1328:19)
    at MessageHandler.send (/usr/src/app/node_modules/pdfjs-dist/build/pdf.worker.js:1059:10)
    at OperatorList.flush (/usr/src/app/node_modules/pdfjs-dist/build/pdf.worker.js:5813:27)
    at /usr/src/app/node_modules/pdfjs-dist/build/pdf.worker.js:28040:22
From previous event:
    at Page.getOperatorList (/usr/src/app/node_modules/pdfjs-dist/build/pdf.worker.js:28034:65)
    at /usr/src/app/node_modules/pdfjs-dist/build/pdf.worker.js:22415:14
From previous event:
    at Object.wphSetupRenderPage (/usr/src/app/node_modules/pdfjs-dist/build/pdf.worker.js:22410:37)
    at LoopbackPort.MessageHandler._onComObjOnMessage (/usr/src/app/node_modules/pdfjs-dist/build/pdf.worker.js:1036:19)
    at LoopbackPort.<anonymous> (/usr/src/app/node_modules/pdfjs-dist/build/pdf.js:3835:20)
    at Array.forEach (<anonymous>)
    at /usr/src/app/node_modules/pdfjs-dist/build/pdf.js:3834:27
From previous event:
    at LoopbackPort.postMessage (/usr/src/app/node_modules/pdfjs-dist/build/pdf.js:3833:22)
    at MessageHandler.postMessage (/usr/src/app/node_modules/pdfjs-dist/build/pdf.js:1330:19)
    at MessageHandler.send (/usr/src/app/node_modules/pdfjs-dist/build/pdf.js:1059:10)
    at PDFPageProxy_render [as render] (/usr/src/app/node_modules/pdfjs-dist/build/pdf.js:3582:39)
    at CanvasRenderer.renderPage (/usr/src/app/node_modules/pdf-extractor/lib/renderer/CanvasRenderer.js:87:28)
    at lastPromise.then (/usr/src/app/node_modules/pdf-extractor/lib/PdfExtractor.js:75:21)
From previous event:
    at PdfExtractor.renderPageData (/usr/src/app/node_modules/pdf-extractor/lib/PdfExtractor.js:74:30)
    at doc.getPage.then (/usr/src/app/node_modules/pdf-extractor/lib/PdfExtractor.js:55:59)
From previous event:
    at /usr/src/app/node_modules/pdf-extractor/lib/PdfExtractor.js:55:39
From previous event:
    at PdfExtractor.parseDocument (/usr/src/app/node_modules/pdf-extractor/lib/PdfExtractor.js:62:30)
    at PDFJSLib.getDocument.then (/usr/src/app/node_modules/pdf-extractor/lib/PdfExtractor.js:44:25)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at PDFDocumentLoadingTask_then [as then] (/usr/src/app/node_modules/pdfjs-dist/build/pdf.js:3393:32)
    at PdfExtractor.parseFromFileBuffer (/usr/src/app/node_modules/pdf-extractor/lib/PdfExtractor.js:44:6)
    at PdfExtractor.parse (/usr/src/app/node_modules/pdf-extractor/lib/PdfExtractor.js:31:15)
    at <anonymous>
```

**Comment by Hikariii** [comment]
Fixed with https://github.com/SyslogicNL/pdf-extractor/pull/2
Related to https://github.com/Automattic/node-canvas/issues/487, using Canvas.Image and jsdom canvas reference to stick to the same canvas implementation.
